# Generated by Django 4.2.16 on 2024-11-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_onlinestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinestatus',
            options={'verbose_name_plural': 'OnlineStatus'},
        ),
    ]
