# Generated by Django 4.2.16 on 2024-11-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': 'Stocks'},
        ),
    ]
