version: '3.8'

services:
  showcase:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env  # This will load variables from the ../.env file
    depends_on:
      - redis
    networks:
      - showcase_network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - showcase_network

  celery:
    build: .
    command: celery -A showcase worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ../.env  # This will load variables from the ../.env file
    depends_on:
      - redis
    networks:
      - showcase_network

  celery-beat:
    build: .
    command: celery -A showcase beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ../.env  # This will load variables from the ../.env file
    depends_on:
      - redis
    networks:
      - showcase_network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - showcase_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - showcase_network

volumes:
  redis_data:

networks:
  showcase_network:
    driver: bridge
